"""Round 247: content provenance, the OpenGraph fallbacks, and pronouns.

Three clusters in `app/utils.py`.

`inspect_image_c2pa` reads an uploaded image's C2PA manifest to answer two questions: is
there provenance at all, and does it say the image was generated by a model. The answer sets
`Post.ai_generated`, which viewers filter on -- so a manifest read wrongly either labels
somebody's photograph as AI or lets generated media through a filter somebody asked for. The
whole body is wrapped in `except Exception: pass`, because the input is an arbitrary upload.

`parse_page`'s tail fills in what a page did not give as OpenGraph: a `<meta name=description>`
becomes the description, and a `<title>` becomes `og:title`. These are the values rendered
beside a link post.

`user_pronouns` renders a self-set profile field beside a username, with a length limit and an
HTML escape hatch.
"""
import io
from types import SimpleNamespace
from unittest.mock import patch

import pytest
from flask import g

from app import cache, db
from app.models import Site, UserExtraField
from app.utils import inspect_image_c2pa, parse_page, user_pronouns
from tests.factories import make_user


@pytest.fixture
def env(app, api_baseline):
    g.admin_ids = []
    g.site = db.session.get(Site, 1)
    return SimpleNamespace(app=app, site=g.site, baseline=api_baseline)


# --------------------------------------------------------------------------
# What an image says about where it came from
# --------------------------------------------------------------------------


class _FakeReader:
    """Stands in for `c2pa.Reader`. The real one parses a signed manifest out of image bytes;
    what this module does with the parsed dict is the part under test.
    """

    def __init__(self, manifest):
        self._manifest = manifest

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False

    def get_active_manifest(self):
        return self._manifest


class _FakeContext:
    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False


def _c2pa(manifest, reader_error=None):
    """Patch the `c2pa` module `inspect_image_c2pa` imports inside itself."""
    module = SimpleNamespace(
        Context=lambda: _FakeContext(),
        Reader=(lambda *args, **kwargs: (_ for _ in ()).throw(reader_error))
        if reader_error else (lambda *args, **kwargs: _FakeReader(manifest)))
    return patch.dict('sys.modules', {'c2pa': module})


def actions_manifest(source, action='c2pa.created', generator='Some Camera 1.0'):
    return {'claim_generator': generator,
            'assertions': [{'label': 'c2pa.actions',
                            'data': {'actions': [{'action': action,
                                                  'digitalSourceType': source}]}}]}


class TestReadingAnImagesProvenance:

    def test_an_image_with_no_manifest_says_so(self):
        """The default dict, returned whenever the reader raises -- which is what an
        ordinary photograph with no C2PA data does. Every field is falsy, so a caller that
        checks `['c2pa']['ai_generated']` sees False rather than a KeyError."""
        with _c2pa(None, reader_error=ValueError('no manifest')):
            answer = inspect_image_c2pa(b'not an image', 'image/png')

        assert answer == {'c2pa': {'present': False, 'ai_generated': False,
                                   'creator': None, 'software': None}}

    def test_a_readable_manifest_is_present_even_with_nothing_in_it(self):
        """`present` is set before the manifest is read, so an image carrying an EMPTY
        manifest still reports provenance -- which is the honest answer: something signed
        it."""
        with _c2pa(None):
            answer = inspect_image_c2pa(b'bytes', 'image/jpeg')

        assert answer['c2pa']['present'] is True
        assert answer['c2pa']['creator'] is None

    def test_the_claim_generator_becomes_the_creator(self):
        with _c2pa(actions_manifest('digitalCapture', generator='Fancy Camera 2.0')):
            answer = inspect_image_c2pa(b'bytes', 'image/jpeg')

        assert answer['c2pa']['creator'] == 'Fancy Camera 2.0'

    @pytest.mark.parametrize('action', ['c2pa.created', 'c2pa.placed'])
    def test_a_trained_model_source_marks_the_image_ai_generated(self, action):
        """The answer that matters. `trainedAlgorithmicMedia` is the IPTC term for
        model-generated media, and it is accepted under either action -- `created` for an
        image a model made and `placed` for one composited into another."""
        source = 'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia'
        with _c2pa(actions_manifest(source, action=action)):
            answer = inspect_image_c2pa(b'bytes', 'image/jpeg')

        assert answer['c2pa']['ai_generated'] is True

    def test_a_camera_capture_is_not_ai_generated(self):
        """The control, and the expensive direction: labelling a photograph as AI would put
        a warning on somebody's own picture."""
        source = 'http://cv.iptc.org/newscodes/digitalsourcetype/digitalCapture'
        with _c2pa(actions_manifest(source)):
            answer = inspect_image_c2pa(b'bytes', 'image/jpeg')

        assert answer['c2pa']['ai_generated'] is False
        assert answer['c2pa']['present'] is True

    def test_an_action_this_code_does_not_read_is_ignored(self):
        """`if action_name in [...]`. An `c2pa.edited` action naming a model source says the
        image was EDITED with a model, not generated by one -- a different claim, and not the
        one this flag makes."""
        source = 'trainedAlgorithmicMedia'
        with _c2pa(actions_manifest(source, action='c2pa.edited')):
            answer = inspect_image_c2pa(b'bytes', 'image/jpeg')

        assert answer['c2pa']['ai_generated'] is False

    def test_an_assertion_that_is_not_about_actions_is_ignored(self):
        """`label.startswith('c2pa.actions')`. A manifest carries many assertion types, and
        reading a training-and-data-mining assertion as an action would be a different
        claim again."""
        manifest = {'claim_generator': 'Some Tool',
                    'assertions': [{'label': 'c2pa.training-mining',
                                    'data': {'actions': [
                                        {'action': 'c2pa.created',
                                         'digitalSourceType': 'trainedAlgorithmicMedia'}]}}]}
        with _c2pa(manifest):
            answer = inspect_image_c2pa(b'bytes', 'image/jpeg')

        assert answer['c2pa']['ai_generated'] is False

    def test_a_manifest_with_no_assertions_at_all_is_harmless(self):
        """`manifest.get('assertions', [])` -- the key is optional, and iterating None
        would raise inside the `try`, which would silently become "no provenance" and lose
        the `present` flag the reader had already established."""
        with _c2pa({'claim_generator': 'Some Tool'}):
            answer = inspect_image_c2pa(b'bytes', 'image/jpeg')

        assert answer['c2pa']['present'] is True
        assert answer['c2pa']['creator'] == 'Some Tool'
        assert answer['c2pa']['ai_generated'] is False

    def test_an_action_with_no_source_is_not_ai_generated(self):
        """`action.get('digitalSourceType', '')`. The key is optional, and
        `'x' in None` is a `TypeError`."""
        manifest = {'claim_generator': 'Some Tool',
                    'assertions': [{'label': 'c2pa.actions',
                                    'data': {'actions': [{'action': 'c2pa.created'}]}}]}
        with _c2pa(manifest):
            answer = inspect_image_c2pa(b'bytes', 'image/jpeg')

        assert answer['c2pa']['ai_generated'] is False


# --------------------------------------------------------------------------
# What a page tells us about itself
# --------------------------------------------------------------------------


class TestReadingAPagesMetaTags:
    """`parse_page` fetches a URL and reads its OpenGraph tags; its tail fills in from
    ordinary HTML what the page did not say in `og:`. These values are rendered beside a link
    post, so the fallbacks decide what a reader sees for a page with no OpenGraph at all.
    """

    def _parse(self, html):
        """`parse_page` fetches through `get_request`, which is memoized and does its own
        SSRF checking -- so the fetch is replaced at that level rather than at the http
        client."""
        response = SimpleNamespace(
            status_code=200,
            headers={'Content-Type': 'text/html'},
            text=html,
            content=html.encode(),
            close=lambda: None)
        with patch('app.utils.get_request', return_value=response):
            return parse_page('https://news.example/story')

    def test_a_pages_opengraph_tags_are_read(self):
        tags = self._parse('<html><head>'
                           '<meta property="og:title" content="A Story">'
                           '<meta property="og:image" content="https://x/y.png">'
                           '</head><body></body></html>')

        assert tags['og:title'] == 'A Story'
        assert tags['og:image'] == 'https://x/y.png'

    def test_a_plain_description_meta_is_used(self):
        """`<meta name="description">` is what most pages have and OpenGraph is what few of
        them have, so this fallback is the common case rather than the edge one."""
        tags = self._parse('<html><head>'
                           '<meta property="og:title" content="A Story">'
                           '<meta name="description" content="what it is about">'
                           '</head></html>')

        assert tags['description'] == 'what it is about'
        assert tags['og_description'] == 'what it is about'

    def test_an_opengraph_description_is_copied_to_the_plain_key(self):
        """The other direction: a page with only `og:description` gets `description` too, so
        a caller reading either key finds it."""
        tags = self._parse('<html><head>'
                           '<meta property="og:title" content="A Story">'
                           '<meta property="og:description" content="from opengraph">'
                           '</head></html>')

        assert tags['description'] == 'from opengraph'

    def test_a_page_with_both_descriptions_keeps_them_apart(self):
        """`if "og:description" not in found_tags`. A page that gives both gets
        `description` from the plain meta and `og:description` under its own key -- and NOT
        `og_description`, which exists only as a stand-in for a page that has no OpenGraph
        description at all. Without that test the stand-in would shadow the real one.
        """
        tags = self._parse('<html><head>'
                           '<meta property="og:title" content="A Story">'
                           '<meta property="og:description" content="from opengraph">'
                           '<meta name="description" content="from the plain meta">'
                           '</head></html>')

        assert tags['og:description'] == 'from opengraph'
        assert tags['description'] == 'from the plain meta'
        assert 'og_description' not in tags

    def test_the_title_element_stands_in_for_a_missing_og_title(self):
        """`if len(found_tags) == 0 or 'og:title' not in found_tags`. Without this a page
        with no OpenGraph shows a link post with no title at all."""
        tags = self._parse('<html><head><title>The Real Title</title></head></html>')

        assert tags['og:title'] == 'The Real Title'

    def test_a_page_with_an_og_title_keeps_it(self):
        """The `<title>` is usually the site name appended to the headline, so it must not
        override a page that said what it wanted."""
        tags = self._parse('<html><head>'
                           '<meta property="og:title" content="The Headline">'
                           '<title>The Headline | Some Site</title>'
                           '</head></html>')

        assert tags['og:title'] == 'The Headline'

    def test_a_page_with_nothing_readable_gives_nothing(self):
        """`if title:` -- a page with neither OpenGraph nor a `<title>`. The answer is an
        empty dict, which every caller tests for before using it."""
        assert self._parse('<html><body>just words</body></html>') == {}


# --------------------------------------------------------------------------
# Pronouns beside a username
# --------------------------------------------------------------------------


class TestThePronounsShownBesideAName:
    """A self-set profile field, rendered beside the username everywhere it appears. That
    makes it attacker-controlled display text, which is what the length limit and the HTML
    handling are for.
    """

    @pytest.fixture
    def real_cache(self, app, monkeypatch):
        from cachelib import SimpleCache

        monkeypatch.setitem(app.extensions['cache'], cache, SimpleCache())
        cache.delete_memoized(user_pronouns)
        return cache

    def _field(self, env, user, label, text):
        db.session.add(UserExtraField(user_id=user.id, label=label, text=text))
        db.session.commit()
        cache.delete_memoized(user_pronouns)

    @pytest.mark.parametrize('label', ['Pronouns', 'pronouns', 'PRONOUNS'])
    def test_the_field_is_matched_case_insensitively(self, env, real_cache, label):
        """`func.lower(label) == 'pronouns'`. The label is typed by the account holder, so
        the capitalisation is theirs."""
        user = make_user(env.baseline.instance_local, f'person{label}', local=True)
        db.session.commit()
        self._field(env, user, label, 'they/them')

        assert user_pronouns()[user.id] == 'they/them'

    def test_a_long_value_is_not_shown_at_all(self, env, real_cache):
        """`len(text) <= 22`. The value goes beside a username in every listing, so an
        overlong one is dropped rather than truncated -- a cut-off pronoun would be worse
        than none."""
        user = make_user(env.baseline.instance_local, 'verbose', local=True)
        db.session.commit()
        self._field(env, user, 'Pronouns', 'x' * 23)

        assert user.id not in user_pronouns()

    def test_a_value_of_exactly_the_limit_is_shown(self, env, real_cache):
        user = make_user(env.baseline.instance_local, 'exact', local=True)
        db.session.commit()
        self._field(env, user, 'Pronouns', 'x' * 22)

        assert user_pronouns()[user.id] == 'x' * 22

    def test_markup_is_reduced_to_text(self, env, real_cache):
        """`if '<' in text and '>' in text: html_to_text(...)`. The field is rendered beside
        a name, and this is the line that stops somebody's 'pronouns' being markup."""
        user = make_user(env.baseline.instance_local, 'markupper', local=True)
        db.session.commit()
        self._field(env, user, 'Pronouns', '<b>they</b>')

        assert user_pronouns()[user.id] == 'they'

    def test_a_missing_account_has_no_pronouns(self, env, real_cache):
        """The return is a `defaultdict(str)`, so a template asking about any account gets
        an empty string rather than a KeyError -- which is what lets the caller render it
        unconditionally."""
        assert user_pronouns()[999999] == ''
